Repository Crystal-Creations-GbR/animated-checkmark, pull requests merged in 2022-10, with the labels that each got.

#32 build(deps-dev): update dev-dependencies
  package-lock.json
  package.json
Labels: dependencies

#33 build: distribute properly built files
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  rollup.config.js
  src/index.ts
  src/shims-tsx.d.ts
  src/shims-vue.d.ts
  tsconfig.json
Labels: enhancement

#36 feat: add property `color`
  src/AnimatedCheckmark.vue
Labels: enhancement

#37 fix: remove color from `fill` and `stroke`
  src/AnimatedCheckmark.vue
Labels: bug
